version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_volume:/data/db
    networks:
      - mongo_network
  

      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - mongo_network



  backend:
    image: evelynemwende/yolo-backend:v1.0.1
    depends_on:
      - mongo
    ports:
     - 5000:5000
    environment:
      - DB_HOST=mongo
      - DB_USER=admin
      - DB_PASSWORD=password
    volumes:
      - mongo_volume:/data/db
    networks:
      - mongo_network



  client:
    image: evelynemwende/yolo-client:v1.0.1
    ports:
     - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
      - backend  
    networks:
      - mongo_network
    volumes:
      - mongo_volume:/data/db

volumes:
  mongo_volume:
    driver: local

networks:
  mongo_network:
    external: true