version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb

  backend:
    build:
      context: backend
      dockerfile: ./Dockerfile
    depends_on:
      - mongodb
    ports:
     - 5000:5000

  client:
    build:
      context: client
      dockerfile: ./Dockerfile
    depends_on:
      - mongodb
    ports:
     - 3000:3000
    