---
- name: Setup
  hosts: all
  become: true
  vars:
    client_image: evelynemwende/yolo-client:v1.0.1
    backend_image: evelynemwende/yolo-backend:v1.0.1
    mongo_image: mongo
    NODEJS_VERSION: "16"
    # default_container_command: sleep 1

  roles:
    - common

