---
- name: Setup
  hosts: all
  become: true
  vars:
    client_image: evelynemwende/yolo-client:v1.0.1
    backend_image: evelynemwende/yolo-backend:v1.0.1
    mongo_image: mongo
    NODEJS_VERSION: "16"
    # default_container_command: sleep 1

  roles:
    - common

- name: Pull mongo image and launch container
  hosts: all
  become: true
  tags: mongo
  roles:
    - db

- name: Pull backend image and launch container
  hosts: all
  become: true
  tags: backend
  roles:
    - backend

- name: Pull client image and launch container
  hosts: all
  become: true
  tags: client
  roles:
    - client