---
- name: Run backend container
  vars:
    backend_image: evelynemwende/yolo-backend:v1.0.1
  docker_container:
    name: yolo-backend
    image: evelynemwende/yolo-backend:v1.0.1
    ports:
      - "5000:5000"
    volumes:
      - mongo_volume   
    state: started
  
- name: Add backend to the network
  docker_network:
    name: mongo_network
    connected:
      - yolo-backend
    appends: true

