---
- name: Run backend container
  vars:
    backend_image: evelynemwende/yolo-backend:v1.0.2
  docker_container:
    name: yolo-backend
    image: evelynemwende/yolo-backend:v1.0.2
    ports:
      - "5000:5000"
    env:
       DB_HOST=mongodatabase
       DB_USER=admin
       DB_PASSWORD=password
      
    volumes:
      - mongo_volume:/data/db   
    state: started
  
- name: Add backend to the network
  docker_network:
    name: mongo_network
    connected:
      - yolo-backend
    appends: true

