---
- name: Build backend image
  docker_image:
    build: 
      path: ../roles/backend
      name: yolo_backend
      state: build

- name: Run backend container
  docker_container:
    name: yolo_backend
    image: yolo_backend
    ports: 
      - "5000:5000"
    volumes: 
      - ../roles/backend
    state: running

- name: Check if container is running
  shell: docker ps