---
- name: Create volume for shared data
  docker_volume:
    name: mongo_volume
    state: present

- name: Run MongoDB container
  docker_container:
    name: mongodatabase
    image: mongo
    ports:
      - 27017:27017
    env:
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_ROOT_USERNAME: admin
    volumes:
      - mongo_volume:/data/db
    state: started

- name: Check if container is running
  shell: docker ps

- name: Add mongo_db container to the network
  docker_network:
    name: mongo_network
    connected:
      - mongodatabase
    appends: true

