---
- name: Run client container
  docker_container:
    name: yolo-client
    image: evelynemwende/yolo-client:v1.0.1
    ports:
      - "3000:3000"
    exposed_ports:
      - 3000
    volumes:
      - mongo_volume   
    state: started
  
- name: Add client to the network
  docker_network:
    name: mongo_network
    connected:
      - yolo-client
    appends: true

